name: "Greet on Pull Requests"

on:
  pull_request:
    types: [opened, reopened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Comment Hello World
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            body: "Hello world"
          });